/// <reference types="cypress" />

it ('logintest', function() {
cy.visit('https://twitter.com')
cy.wait(2000)
//cy.get('[data-testid="signupButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
cy.wait(2000)
cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
cy.wait(1000)
cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
cy.wait(2000)
cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
cy.wait(10000)
})

it ('logintest2', function() {
/* verify the username with invalid object */
         cy.visit('https://twitter.com')
         cy.wait(2000)
    //cy.get('[data-testid="signupButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225233')
    cy.wait(2000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    cy.wait(2000)
    //cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    //cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    cy.get('[data-testid="toast"]').should('be.visible')
    cy.wait(10000)
    })

    it ('logintest3', function() {
        /* verify the username with null object */
        cy.visit('https://twitter.com')
        cy.wait(2000)
        //cy.get('[data-testid="signupButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
        cy.wait(2000)
        cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('   ')
        cy.wait(2000)
        cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
        cy.wait(2000)
        //cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
        //cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
        cy.get('[data-testid="toast"]').should('be.visible')
        cy.wait(20000)
        })

        it ('logintest3', function() {
                        /* verify the password with invalid object */
            cy.visit('https://twitter.com')
            cy.wait(2000)
            //cy.get('[data-testid="signupButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
            cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
            cy.wait(2000)
            cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
            cy.wait(2000)
            cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
            cy.wait(2000)
            cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@1')
            cy.wait(2000)
            cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
            cy.get('[data-testid="toast"]').should('be.visible')
            cy.wait(20000)
            })

            it ('logintest3', function() {
                /* verify the password with invalid object */
    cy.visit('https://twitter.com')
    cy.wait(2000)
    //cy.get('[data-testid="signupButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(2000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('  ')
    cy.wait(2000)
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    cy.get('[data-testid="toast"]').should('be.visible')
    cy.wait(20000)
    })