/// <reference types="cypress" />

    it ('twitter login page', function() {
        cy.visit('https://twitter.com')
        cy.wait(2000)
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(1000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    cy.wait(10000)
    })

    it ('twitter properties test', function() {
        cy.visit('https://twitter.com')
        cy.wait(2000)
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(1000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    cy.wait(10000)
    cy.get('.css-4rbku5 > .r-1awozwy > .r-1cvl2hr > g > path').should('be.visible')
    cy.get('[data-testid="AppTabBar_Home_Link"] > .r-1awozwy > .css-1dbjc4n > .r-18jsvk2').should('be.visible')
    cy.get('[data-testid="AppTabBar_Explore_Link"] > .r-1awozwy > .css-1dbjc4n > .r-18jsvk2').should('be.visible')
    cy.get('[data-testid="AppTabBar_DirectMessage_Link"] > .r-1awozwy > .css-1dbjc4n > .r-18jsvk2').should('be.visible')
    cy.get('.r-1h3ijdo > .r-1wbh5a2 > .css-1dbjc4n > .css-4rbku5 > .css-901oao').should('be.visible')
    cy.get('[data-testid="UserAvatar-Container-rashmib1103"] > :nth-child(2) > .r-bztko3 > :nth-child(2) > .r-ggadg3 > .css-4rbku5 > :nth-child(4) > .css-1dbjc4n').should('be.visible')
    cy.get('[href="/rashmib1103/lists"] > .r-1awozwy > .css-1dbjc4n > .r-18jsvk2').should('be.visible')
    })


    it ('twitter search page', function() {
        cy.visit('https://twitter.com')
        cy.wait(2000)
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(1000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    //cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    //cy.wait(10000)
    cy.get('[data-testid="AppTabBar_Explore_Link"] > .r-1awozwy > .css-1dbjc4n > .r-18jsvk2').click()
    cy.get('[data-testid="SearchBox_Search_Input"]').type('narendra modi{enter}')
   // cy.get('[data-testid="18839785-follow"]').click({force:true})
    //cy.get('[data-testid="18839785-unfollow"] > .r-1awozwy').should('be.visible')
    ///unfollow method
    //cy.get('[data-testid="18839785-unfollow"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').should('be.visible')
    cy.get('[data-testid="18839785-unfollow"] > .r-1awozwy').click({force:true})
    })
    

    it.only('twitter message page', function() {
        cy.visit('https://twitter.com')
        cy.wait(2000)
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(1000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    //cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    //cy.wait(10000)
    cy.get('[data-testid="AppTabBar_DirectMessage_Link"] > .r-1awozwy').click()
    cy.get('[data-testid="NewDM_Button"] > .r-1awozwy').click()
    cy.get(':nth-child(2) > .r-1iusvr4 > .r-1wtj0ep > :nth-child(1) > :nth-child(1) > .r-1awozwy.r-1wbh5a2 > .r-1wbh5a2 > .css-1dbjc4n > .css-1hf3ou5 > .css-901oao').click()
    cy.get('[data-testid="nextButton"]').click()
    cy.get('.public-DraftStyleDefault-block').type('hey')
    cy.get('[data-testid="dmComposerSendButton"] > .r-1awozwy').click()
    cy.get('[data-testid="AppTabBar_Home_Link"] > .r-1awozwy').click()
    //cy.get('[data-testid="searchPeople"]').type('kirandeshmukhmath').click({force:true})
    //cy.get('.r-1iusvr4 > .r-1wtj0ep').click({force:true})
    })

    it('twitter edit profile page', function() {
        cy.visit('https://twitter.com')
        cy.wait(2000)
        cy.get('[data-testid="loginButton"] > .r-1awozwy > .css-1hf3ou5 > .css-901oao').click()
    cy.wait(2000)
    cy.get('.r-1ets6dv > :nth-child(1) > .r-16y2uox').type('9019225230')
    cy.wait(1000)
    cy.get('[style="background-color: rgb(15, 20, 25); border-color: rgba(0, 0, 0, 0);"]').click({force:true})
    //cy.wait(2000)
    cy.get('.r-mk0yit.r-13qz1uu > .r-mk0yit').type('Password@123')
    cy.get('[data-testid="LoginForm_Login_Button"]').click({force:true})
    cy.get('[data-testid="AppTabBar_Profile_Link"] > .r-1awozwy').click({force:true})
    cy.get('[data-testid="editProfileButton"]').click({force:true})
   //cy.get('[data-testid="fileInput"]').should('be.visible')
   cy.get(':nth-child(5) > .r-1ets6dv > :nth-child(1) > .r-16y2uox').type('bangalore')
   cy.wait(2000)
 cy.get(':nth-child(4) > .r-1ets6dv > :nth-child(1) > .r-16y2uox > .css-901oao > .r-30o5oe').type('be happy be confident')
   cy.wait(2000)
   cy.get('[data-testid="fileInput"]').attachFile('../fixtures/plant.jpg')
   cy.wait(2000)
   cy.get('[data-testid="Profile_Save_Button"]').click({force:true})
})
    